
########################################################################################
AUTOGENERATED HYPR CONFIG.
PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
########################################################################################

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#

#includes
source=~/.config/hypr/macchiato.conf

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto


# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Some default env vars.
env = XCURSOR_SIZE,24

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = $sky $red $peach 30deg 
    col.inactive_border = $crust $blue $base 40deg

    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10
    
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = $skyAlpha
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic-mouse-v1 {
    sensitivity = -0.5
}

misc {
  suppress_portal_warnings = true  
  disable_hyprland_logo = true
  disable_splash_rendering = true
}

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
#


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, return, exec, [workspace name:foot] foot 
bind = $mainMod SHIFT, Q, killactive, 
bind = $mainMod SHIFT, E, exit, 
bind = $mainMod, M, exec, tere 
bind = $mainMod, space, togglefloating, 
bind = $mainMod, D, exec, fuzzel
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, U, togglesplit, # dwindle

# Move focus with mainMod + arrow keys
bind = $mainMod, j, movefocus, l
bind = $mainMod, semicolon, movefocus, r
bind = $mainMod, l, movefocus, u
bind = $mainMod, k, movefocus, d
bind = $mainMod, f, fullscreen

# Switch workspace%s with mainMod + [0-9]
bind = $mainMod, 1, workspace, name:foot 
bind = $mainMod, 2, workspace, name:firefox 
bind = $mainMod, 3, workspace, name:discord 
bind = $mainMod, 4, workspace, name:rdp/moonlight 
bind = $mainMod, 5, workspace, name:anki 
bind = $mainMod, 6, workspace, name:gaming 
bind = $mainMod, 7, workspace, name:focuswriter 
bind = $mainMod, 8, workspace, name:zathura 
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, name:foot 
bind = $mainMod SHIFT, 2, movetoworkspace, name:firefox 
bind = $mainMod SHIFT, 3, movetoworkspace, name:discord
bind = $mainMod SHIFT, 4, movetoworkspace, name:rdp/moonlight 
bind = $mainMod SHIFT, 5, movetoworkspace, name:anki 
bind = $mainMod SHIFT, 6, movetoworkspace, name:gaming 
bind = $mainMod SHIFT, 7, movetoworkspace, name:focuswriter 
bind = $mainMod SHIFT, 8, movetoworkspace, name:zathura 
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# move active window
bind = $mainMod SHIFT, J, movewindow, l
bind = $mainMod SHIFT, semicolon, movewindow, r 
bind = $mainMod SHIFT, L, movewindow, u 
bind = $mainMod SHIFT, K, movewindow, d 

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# bind to volume keys for pulseAudio
bind = ,code:122, exec, pamixer -d 5
bind = ,code:123, exec, pamixer -i 5
bind = ,code:121, exec, pamixer -t

# grim bind for screenshotting
bind = $mainMod, code:96, exec, grim -o LVDS-1
bind = $mainMod, code:96, exec, grim -o LVDS-2

#bind for rezise mode
bind = $mainMod SHIFT, space, submap, resize
submap=resize

# movement binds
binde=,semicolon,resizeactive, 40 0
binde=,J,resizeactive, -40 0
binde=,K,resizeactive, 0 40
binde=,L,resizeactive, 0 -40

# BIG resize binds
binde=SHIFT,semicolon,resizeactive, 120 0
binde=SHIFT,J,resizeactive, -120 0
binde=SHIFT,K,resizeactive, 0 120
binde=SHIFT,L,resizeactive, 0 -120


bind=,escape,submap,reset
submap=reset

#startup
exec-once=waybar
# exec-once=mpvpaper -p -o "no-audio loop-file=inf speed=0.91" '*' truepaper.webm
exec-once=hyprpaper
exec-once=[workspace name:foot;float; size 1024 720;center] foot -H /home/Nolan/startup.sh
# workspace placement
windowrule = workspace name:firefox, ^(firefox)$
windowrule = workspace name:discord, ^(discord)$
windowrule = workspace name:rdp/moonlight ^(moonlight)$
windowrule = workspace name:anki, ^(anki)$
windowrule = workspace name:focuswriter, ^(focuswriter)$
windowrule = workspace name:zathura, ^(org.pwmt.zathura)$

# workspace names
workspace = name:foot, default:true
# custom reserved area waybar
monitor=LVDS-1,addreserved,-10,0,0,0
monitor=LVDS-2,addreserved,-10,0,0,0
